name: Deploy

on:
  push:
    branches:
      - master
  status:
    if_error_or_failure:
      runs-on: ubuntu-latest
      if: ${{ github.event.state == 'error' || github.event.state == 'failure' }}
      steps:
        - uses: s3krit/matrix-message-action@v0.0.3
        - with:
            room_id: ${{ secrets.MATRIX_ROOM_ID }}
            access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
            server: ${{ secrets.MATRIX_SERVER }}
            message: "Error updating metadata! ❌
                ${{ github.event.description }}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run verifier
        run: make verifier

      - name: ⚙ Run collector
        run: make collector

      - uses: ./.github/workflows/deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
